
FROM mongo:latest

EXPOSE 27017


#   mongodb:
#     # database
#     image: mongo:latest
#     container_name: mongodb
#     env_file:
#       - .env
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db
#     restart: unless-stopped