
FROM minio/minio:latest

EXPOSE 9000
EXPOSE 9001


#   minio:
#     # object storage
#     image: minio/minio:latest
#     container_name: minio
#     env_file:
#       - .env
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     volumes:
#       - minio_data:/data
#     command: server /data --console-address ":9001"
#     restart: unless-stopped